spring:
  application:
    name: chicken
  jpa:
    show-sql: true
jwt:
  secret-key: and0U2VjcmV0a2V5bXVzdGJlbG9uZ2VydGhhbjMyY2hhcmFjdGVyc2JlY2FyZWZ1bHdoZW55b3VjaGFuZ2VpdA==
  expiration-time: 3000

s3:
  bucket-name: ktproject-s3-bucket
  product-bucket-url: https://ktproject-s3-bucket.s3.ap-northeast-2.amazonaws.com/products/
  access-key: AKIA4L74ZRT2IIXTSJ2K
  secret-key: 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