spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:ktdarius.test@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: chicken

  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}/${DB_NAME:chicken_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME:15}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:21600}

s3:
  bucket-name: ${S3_BUCKET_NAME:bcm-s3-storage}
  product-bucket-url: ${S3_BUCKET_URL:https://bcm-s3-storage.s3.ap-northeast-2.amazonaws.com/products/}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}